site:
  title: "APPUiO OpenShift 4"
  url: https://openshift.docs.vshn.ch/
  start_page: oc4::index.adoc
  robots: disallow
content:
  sources:
  - url: .                 # The current folder is a git repo
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: docs
    edit_url: 'https://github.com/appuio/openshift4-docs/edit/master/{path}'
ui:
  bundle:
    url: https://github.com/vshn/antora-ui-default/releases/download/1.6/ui-bundle.zip
    snapshot: false
asciidoc:
  attributes:
    toc: 'auto'
    toc-title: ''
    toclevels: 2
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    icons: font
    kroki-server-url: https://vshn-kroki.appuioapp.ch
    kroki-fetch-diagram: ''
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: ./_public
    clean: true
  - provider: archive
    path: ./_archive/site.zip
    clean: true

